name: qeep pr

on:
  pull_request:
    types: [opened, edited, reopened]

env:
  TITLE: ${{ github.event.pull_request.title }}
  TITLE_PATTERN: '^(feat|fix|test|perf|refactor|docs)\((\w+)\)\: (.{1,50})$'

jobs:
  PR:
    runs-on: ubuntu-latest
    steps:
      - name: Title Validation
        run: |
          echo $TITLE
          PR_TITLE="${{ github.event.pull_request.title }}"
          if [[ ! "$PR_TITLE" =~ $PR_TITLE_REGEX ]]; then
            echo "Invalid PR title: $PR_TITLE"
            exit 1
          fi
