name: qeep pulling

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened

env:
  PR_TITLE_REGEX: '^(feat|fix|test|perf|refactor|docs)\((\w+)\)\: (.{1,50})$'
  PR_DESCRIPTION_REGEX: "^(.{0,72}$).*"
  SCRIPTS_ROOT: ./.github/scripts

jobs:
  validate-title:
    runs-on: ubuntu-latest

    steps:
      - name: Validate PR Title
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          if [[ ! "$PR_TITLE" =~ $PR_TITLE_REGEX ]]; then
            echo "Invalid PR title: $PR_TITLE"
            exit 1
          else
            echo "Valid PR title: $PR_TITLE"
          fi
